### ISSUE TITLE
change default logo from "MarkLogic" to "Powered by MarkLogic"

### ISSUE THREAD

**Issue by patrickmcelwee** [marklogic-community/slush-marklogic-node#434]
Feedback from my SEs (specifically Scott Fowler) is that whenever the "MarkLogic" logo is in the top left, recipients of a demo presentation often get confused, thinking that the demo *is* an official front-end to MarkLogic. "Powered by MarkLogic" could help make that more clear.

I know that we typically replace that logo, but do people agree that replacing the default would be helpful?

**Comment by jenbreese** [comment]
We can remove/replace that top logo with a plain <h1>Your Application title here</h1>. I don't think we need a dummy logo to replace the ML one since we might have the same issue. We already have the powered by logo in the footer. It would look funny up in the header as it is intended as a footer type image.

**Comment by patrickmcelwee** [comment]
Or maybe just "Sample Application", since that's what we have on the default search page (I think)

**Comment by jenbreese** [comment]
Oh yes, that is what it was. Do other people feel this way as well or is it only one person?

**Comment by patrickmcelwee** [comment]
I've only heard this from one person

**Comment by grtjn** [comment]
I wouldn't mind replacing the top-left logo with something along the lines of "Sample Application". Could we do something with @app-name? Feel free to open a PR against the cards-theme branch. If you do, I might include it in 1.3.0.. :)

**Comment by grtjn** [comment]
I often find myself just trading out the logo image with a different one. I like having stub code in place for showing a logo. We could add some comments or docs that tell how to hide the logo to show app-name instead?

I do see the point of having generic demos that carry the ML logo at the top instead of the PoweredByML logo. We should probably edit those, but that is out of scope of this project. Then again, in this respect replacing the ML logo with the poweredby one, at the top I mean, does make sense..
